name: Viaanix Deploy Scripts
description: Deploy an AWS SAM Application
author: Viaanix | Kelsi Andrews <kelsi.andrews@viaanix.com>
inputs:
  tags:
    description: Tags for All AWS Resources
    required: true
  #    default:
  region:
    description: The AWS Region for All AWS Resources
    required: true
    default: us-east-1
  application-name:
    description: The Name of the Application
    required: true
    default: NoApplicationNameProvided
  aws-account-id:
    description: The AWS Account ID for the Account that the GitHub Actions Runner Will Assume
    required: true
  environment:
    description: The Environment of the Application
    required: true
    default: DEV
  oidc-url:
    description: The URL Used for Verifying GitHub Authorization with AWS
    required: true
  oidc-thumbprint:
    description: The Thumbprint Used for Verifying GitHub Authorization with AWS
    required: true
  ec2:
    description: Specifies if EC2 Permissions Are Needed
    required: false
    default: 'false'
  eventbridge:
    description: Specifies if EventBridge Permissions Are Needed
    required: false
    default: 'false'
  lambda:
    description: Specifies if Lambda Permissions Are Needed
    required: false
    default: 'false'
  sqs:
    description: Specifies if SQS Permissions Are Needed
    required: false
    default: 'false'
  ssm:
    description: Specifies if SSM Permissions Are Needed
    required: false
    default: 'false'
  vpc:
    description: Specifies if VPC Permissions Are Needed
    required: false
    default: 'false'
  iot:
    description: Specifies if IoT Permissions Are Needed
    required: false
    default: 'false'

#outputs:
#  CreateDeployRole:
#    description: 'TODO: ADD' # TODO: ADD
#  CreateS3Bucket:
#    description: 'TODO: ADD' # TODO: ADD
#  Deploy:
#    description: 'TODO: ADD' # TODO: ADD
#  Docker:
#    description: 'TODO: ADD' # TODO: ADD
#    default:
#    default: ${{ github.token }}
#  working-directory:
#    description: 'Relative path under $GITHUB_WORKSPACE where the repository was checked out.'
#    required: false
#  ref:
#    description: |
#      Git reference (e.g. branch name) from which the changes will be detected.
#      This option is ignored if action is triggered by pull_request event.
#    required: false

#outputs:
#  tbd:
#    description: tbd

runs:
#  entrypoint: ./deploy-scripts/deploy.sh
  using: docker
  image: Dockerfile
  env:
    AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
    #    REPO_URL: ${{ github.server_url}}/${{ github.repository }}
    #    ORG_URL: ${{ github.server_url}}
    ENVIRONMENT: ${{ inputs.environment }}
    TAGS: ${{ inputs.tags }}
    REGION: ${{ inputs.region }}
    APPLICATION_NAME: ${{ inputs.application-name }}
    ROLE_ARGS: ${{ inputs.ec2 == 'true' && 'ec2 ' || '' }}${{ inputs.eventbridge == 'true' && 'eventbridge ' || '' }}${{ inputs.lambda == 'true' && 'lambda ' || '' }}${{ inputs.sqs == 'true' && 'sqs ' || '' }}${{ inputs.ssm == 'true' && 'ssm ' || '' }}${{ inputs.vpc == 'true' && 'vpc ' || '' }} ${{ inputs.iot == 'true' && 'iot' || '' }}
    OIDC_URL: ${{ inputs.oidc-url }}
    OIDC_THUMBPRINT: ${{ inputs.oidc-thumbprint }}

#  steps:
#    - name: Setup Env
#      id: SetupEnv
#      run: |
#        LOWERCASE_APPLICATION_NAME="$(echo "${{ env.APPLICATION_NAME }}" | sed -e 's|\([A-Z][^A-Z]\)| \1|g' -e 's|\([a-z]\)\([A-Z]\)|\1 \2|g' | sed 's/^ *//g' | tr '[:upper:]' '[:lower:]' | tr " " "-")-$(echo "${{ env.ENVIRONMENT }}" | tr '[:upper:]' '[:lower:]')"
#        echo "LOWERCASE_APPLICATION_NAME=$LOWERCASE_APPLICATION_NAME" >> "$GITHUB_OUTPUT"
#        echo "SAM_MANAGED_BUCKET=${LOWERCASE_APPLICATION_NAME}-sam-managed-$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
#  args:
#branding:
#  color: blue
#  icon: filter