name: Setup Environment
description: Setup Environment for Deploying an AWS SAM Application
author: Viaanix | Kelsi Andrews <kelsi.andrews@viaanix.com>
inputs:
  application-name:
    description: The Name of the Application
    required: true
    default: NoApplicationNameProvided
  environment:
    description: The Environment of the Application
    required: true
    default: DEV

outputs:
  LOWERCASE_APPLICATION_NAME:
      description: The Lowercase Version of the Application Name
  SAM_MANAGED_BUCKET:
      description: The S3 Bucket for SAM Managed Resources
  RUNNER_ACCOUNT_ID:
      description: The AWS Account ID for the GitHub Actions Runner

runs:
  using: docker
  image: Dockerfile
  env:
    #    ENVIRONMENT: ${{ github.ref == 'main' && 'PROD' || 'DEV' }}
#    RUNNER_ACCOUNT_ID: ${{ inputs.runner-account-id }}
    #    REPO_URL: ${{ github.server_url}}/${{ github.repository }}
    #    ORG_URL: ${{ github.server_url}}
#    TAGS: ${{ inputs.tags }}
#    REGION: ${{ inputs.region }}
    APPLICATION_NAME: ${{ inputs.application-name }}
    ENVIRONMENT: ${{ inputs.environment }}
#    ROLE_ARGS: ${{ inputs.ec2 == 'true' && 'ec2 ' || '' }}${{ inputs.eventbridge == 'true' && 'eventbridge ' || '' }}${{ inputs.lambda == 'true' && 'lambda ' || '' }}${{ inputs.sqs == 'true' && 'sqs ' || '' }}${{ inputs.ssm == 'true' && 'ssm ' || '' }}${{ inputs.vpc == 'true' && 'vpc' || '' }}
#  steps:
#    - shell: bash
#      run: |
#        LOWERCASE_NAME="$(echo "${{ env.APPLICATION_NAME }}" | sed -e 's|\([A-Z][^A-Z]\)| \1|g' -e 's|\([a-z]\)\([A-Z]\)|\1 \2|g' | sed 's/^ *//g' | tr '[:upper:]' '[:lower:]' | tr " " "-")"
#        LOWERCASE_APPLICATION_NAME="$LOWERCASE_NAME-$(echo "${{ env.ENVIRONMENT }}" | tr '[:upper:]' '[:lower:]')"
#        echo "LOWERCASE_APPLICATION_NAME=$LOWERCASE_APPLICATION_NAME" >> $GITHUB_OUTPUT
#        echo "SAM_MANAGED_BUCKET=$LOWERCASE_NAME-sam-managed-$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

#  steps:
#    - name: Setup Env
#      id: SetupEnv
#      run: |
#        LOWERCASE_APPLICATION_NAME="$(echo "${{ env.APPLICATION_NAME }}" | sed -e 's|\([A-Z][^A-Z]\)| \1|g' -e 's|\([a-z]\)\([A-Z]\)|\1 \2|g' | sed 's/^ *//g' | tr '[:upper:]' '[:lower:]' | tr " " "-")-$(echo "${{ env.ENVIRONMENT }}" | tr '[:upper:]' '[:lower:]')"
#        echo "LOWERCASE_APPLICATION_NAME=$LOWERCASE_APPLICATION_NAME" >> $GITHUB_OUTPUT
#        echo "SAM_MANAGED_BUCKET=${LOWERCASE_APPLICATION_NAME}-sam-managed-$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
#  args:
#branding:
#  color: blue
#  icon: filter

# Setup Environment Variables
#SetupEnv:
#  runs-on: self-hosted
#  environment: ${{ github.ref == 'main' && 'PROD' || 'DEV' }}
#  defaults:
#    run:
#      working-directory: ${{ github.workspace }}
#  env:
#    APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
#    ENVIRONMENT: ${{ github.ref == 'main' && 'PROD' || 'DEV' }}
#  outputs:
#    LOWERCASE_APPLICATION_NAME: ${{ steps.SetupEnv.outputs.LOWERCASE_APPLICATION_NAME }}
#    SAM_MANAGED_BUCKET: ${{ steps.SetupEnv.outputs.SAM_MANAGED_BUCKET }}
#  steps:
#    - name: Setup Env
#      id: SetupEnv
#      run: |
#        LOWERCASE_NAME="$(echo "${{ env.APPLICATION_NAME }}" | sed -e 's|\([A-Z][^A-Z]\)| \1|g' -e 's|\([a-z]\)\([A-Z]\)|\1 \2|g' | sed 's/^ *//g' | tr '[:upper:]' '[:lower:]' | tr " " "-")"
#        LOWERCASE_APPLICATION_NAME="$LOWERCASE_NAME-$(echo "${{ env.ENVIRONMENT }}" | tr '[:upper:]' '[:lower:]')"
#        echo "LOWERCASE_APPLICATION_NAME=$LOWERCASE_APPLICATION_NAME" >> $GITHUB_OUTPUT
#        echo "SAM_MANAGED_BUCKET=$LOWERCASE_NAME-sam-managed-$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT